version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=votacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - votacao-network

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      - postgres
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/votacao
      spring.datasource.username: postgres
      spring.datasource.password: password

      # spring.jpa.hibernate.ddl-auto: update
      spring.profiles.active: docker
    ports:
      - "8080:8080"
    networks:
      - votacao-network

networks:
  votacao-network:
    driver: bridge

volumes:
  postgres_data:
