ALTER TABLE pauta
  ADD COLUMN votos_contra   INTEGER DEFAULT 0,
  ADD COLUMN votos_favor    INTEGER DEFAULT 0,
  ADD COLUMN votos_totais   INTEGER DEFAULT 0,
  ADD COLUMN resultado      CHARACTER(20) DEFAULT 'INDECISIVO';
